### ISSUE TITLE
Add Cover Image Block Styles

### ISSUE THREAD

**Issue by kjohnson** [pluginarchitect/wp-theme-pluginarchitect#9]
The Cover Image Block should probably break-out of the content wrapper on larger screens.

Something like:

```css
@media (min-width: 600px){
    .wp-block-cover-image {
        width: 150%; // Break-out of content wrapper.
        margin-left: -25%; // Adjust alignment to compensate for the change in size.
    }
}
```
